{{- if .Values.kmip.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudserver.fullname" . }}-kmip-cert
  labels:
    app: {{ template "cloudserver.name" . }}
    chart: {{ template "cloudserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{ (.Files.Glob "kmip-*.pem").AsSecrets | indent 2 }}
{{ end }}
