{{- if and .Values.cosmos.enabled (not .Values.cosmos.ci) }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cosmoses.zenko.io
  labels:
    app: {{ template "cosmos-operator.name" . }}
    chart: {{ template "zenko.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook-weight": "-5"
spec:
  group: zenko.io
  names:
    kind: Cosmos
    listKind: CosmosList
    plural: cosmoses
    singular: cosmos
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
{{- end -}}
