{{- if and .Values.cosmos.enabled (not .Values.cosmos.storageClass) }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ template "cosmos-operator.storageclass" . }}
  labels:
    app: {{ template "cosmos-operator.name" . }}
    chart: {{ template "zenko.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
{{- end -}}
