{{- if and .Values.cosmos.enabled .Values.cosmos.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cosmos-scheduler.fullname" . }}
  labels:
    app: {{ template "cosmos-scheduler.name" . }}
    chart: {{ template "zenko.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
